[package]
name = "create-bundle"
version = "0.1.0"
edition = "2021"

[dependencies]
tar = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
regex = "1"
walkdir = "2.3.1" 
zstd = { version = "0.9", features = ["zstdmt"] }