# Used as an override for the test docker-file to add HTTPS to minio and our app
version: '3'
services:
  s3:
    build:
      dockerfile: minio.dockerfile
      context: .


  nginx:
    build:
      dockerfile: nginx.dockerfile
      context: .
    network_mode: "host"
