# Used as an override on prod to provide HTTP basic auth to admin API
version: '3'
services:
  api:
    labels:
      - "traefik.http.routers.admin.tls=true"
      - "traefik.http.routers.admin.tls.certresolver=cloudflareresolver"
      - "traefik.http.routers.admin.rule=Host(`${PUBLIC_HOST}`) && PathPrefix(`/api/admin`)"
      - "traefik.http.middlewares.admin-basic.basicauth.users=admin:this is purposely bad"
      - "traefik.http.routers.admin.middlewares=admin-basic@docker"
