[package]
name = "pdx"
version = "0.1.0"
edition = "2021"
publish = false

[features]
admin = ["create_bundle", "fetch_assets", "tokenize"]
create_bundle = ["dep:zstd"]
fetch_assets = ["dep:aws-config", "dep:aws-sdk-s3", "dep:tokio", "dep:tokio-stream"]
tokenize = ["dep:brotli", "dep:schemas"]

[dependencies]
anyhow = "1.0"
aws-config = { version = "0.15.0", optional = true }
aws-sdk-s3 = { version = "0.15.0", optional = true }
brotli = { version = "3.3", optional = true }
chrono = "0.4"
clap = { version = "3.2", features = ["derive", "env"] }
env_logger = "0.9"
filetime = "0.2"
log = "0.4"
regex = "1"
schemas = { path = "../schemas", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
tokio = { version = "1", features = ["full"], optional = true }
tokio-stream = { version = "0.1.8", optional = true }
walkdir = "2.3.1"
zstd = { version = "0.9", features = ["zstdmt"], optional = true }
