[package]
name = "wasm-hoi4"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1", features = ["derive"] }
hoi4save = "0.1"
js-sys = "0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false