[package]
name = "wasm-hoi4"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
jomini = "0.19"
schemas = { path = "../schemas" }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
serde = { version = "1", features = ["derive"] }
hoi4save = "0.3"
js-sys = "0.3"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false