[package]
name = "eu4game"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2018"
publish = false

[features]
default = ["embedded"]
embedded = []

[dependencies]
jomini = "0.18"
eu4save = { git = "https://github.com/rakaly/eu4save.git" }
schemas = { path = "../schemas" }
tarsave = { path = "../tarsave" }
serde = { version = "1", features = ["derive"] }
highway = "0.7"
base64 = "0.13"

[dev-dependencies]
attohttpc = "0.18"
walkdir = "2"
zip = { version =  "0.5", default-features = false, features = ["deflate"] }

[build-dependencies]
regex = "1.5"