[package]
name = "eu4game"
version = "0.1.0"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
edition = "2021"
publish = false

[features]
default = ["embedded", "miniz"]
miniz = ["eu4save/miniz"]
libdeflate = ["eu4save/libdeflate"]
embedded = []

[dependencies]
jomini = "0.20"
eu4save = { git = "https://github.com/rakaly/eu4save.git", default-features = false }
schemas = { path = "../schemas", features = ["inline"] }
tarsave = { path = "../tarsave" }
serde = { version = "1", features = ["derive"] }
highway = "0.8"
base64 = "0.13"
thiserror = "1"

[dev-dependencies]
attohttpc = "0.19"
walkdir = "2"
zip = { version =  "0.6", default-features = false, features = ["deflate"] }

[build-dependencies]
regex = "1.5"